### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by bodagetta** [joshsymonds/huey#6]
I set up a very simple rails app, this is the controller

```
def index
        Huey.configure do |config|
            # For discovering the Hue hub, usually you won't have to change this
            config.ssdp_ip = '192.168.5.5' 
        end

        @bulbs = Huey::Bulb.all
    end
```

and I get this error

```
Errno::ECONNREFUSED in ControlController#index

Connection refused - connect(2)
```

Should I be authorizing somehow or creating a new user as described here? 
http://developers.meethue.com/gettingstarted.html

**Comment by joshsymonds** [comment]
I would set up Huey in an initializer for your Rails application, rather than in a controller action.

That said, you're setting the SSDP_IP incorrectly. It should be set to the SSDP multicast address, which for most home networks is 239.255.255.250. Don't set it to the IP address of your Hue hub -- SSDP is intended to be used to discover that address without you having to enter it in manually.

**Comment by bodagetta** [comment]
Thanks for the information about SSDP. I haven't used that protocol before. 

I stripped down my controller to just this

```
class ControlController < ApplicationController
    def index
        @bulbs = Huey::Bulb.all
    end
end
```

and I get the same error

Errno::ECONNREFUSED in ControlController#index

Connection refused - connect(2)

any idea how I can start troubleshooting this?

**Comment by bodagetta** [comment]
I took a look at the packets with Packet Peeper on OSX. I see the bridge responding to the SSDP and then my computer tries to send an ICMP packet, but the response is "Destination unreachable: Port unreachable (error)".  I am able to get to my bridge using the IP address listed.
